tutorial:
  ruby_on_rails_tutorial: "https://www.railstutorial.org/"
  contact_page: "https://www.railstutorial.org/contact"
  rails_tutorial_help_page: "https://www.railstutorial.org/help"
  ruby_on_rails_utorial_book: "https://www.railstutorial.org/book"
  learn_enough: "https://www.learnenough.com/"
  screencast_series: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
